### ISSUE TITLE
This logic will not work when multiple people are using the button

### ISSUE THREAD

**Issue by PLASMAchicken** [broke-protocol/broke-protocol#47]
This logic will not work when multiple people are using the button and cause the Button's custom environment to be on forever.

https://github.com/broke-protocol/broke-protocol/blob/ff3db81e03fc8f074a460b6b7293cfc23f04f53e/BP-GameSource/CustomEvents.cs#L64-L72

**Comment by NongBenz** [comment]
Thanks, fixed now:
https://github.com/broke-protocol/broke-protocol/commit/2a41fa383baea0a49338e3e067d8caa460d933aa
