### ISSUE TITLE
Range checks on door enter.

### ISSUE THREAD

**Issue by ggggg** [broke-protocol/broke-protocol#52]
**Describe the bug**
The lack of distance checking on doors entrance could allow cheaters to instantly teleport between locations.

**Expected behavior**
The client packet should be ignored if the player isn't in action range of the door

**Additional context**
See: #51

**Comment by PLASMAchicken** [comment]
https://github.com/broke-protocol/broke-protocol/blob/5f4485167f4eddb666d94f0ac5b0e013c5b0b49f/GameSource/Types/Player.cs#L614C52
