### ISSUE TITLE
[SVR] %player.username% tried to remove an invalid amount from inventory

### ISSUE THREAD

**Issue by PLASMAchicken** [broke-protocol/broke-protocol#56]
https://github.com/broke-protocol/broke-protocol/blob/9e7f963d796206386500a563bbb1da14cbe7a52e/GameSource/Types/Player.cs#L325-L332

The code in GameSource Player does not check if the player has eneugh mone,y causing the permanent warnings in console each time a crime is commited.

**Comment by NongBenz** [comment]
Fixed in GameSource develop. Thanks for reporting
https://github.com/broke-protocol/broke-protocol/commit/ed018d548d5877814f1caf19a5aba287bd1adad5
